### ISSUE TITLE
Initialization/starting app

### ISSUE THREAD

**Issue by curiousYi** [feihong/react-quickstart#1]
Not sure what's going on, but it looks like your `webpack.config` is broken? 

![image](https://user-images.githubusercontent.com/19179930/42481145-835e8d36-83a6-11e8-91b1-d6647e6022e5.png)

nit - Does Glitch not allow `yarn`? I'm confused why you have `npm start` in the README.md but everywhere else it uses `yarn`. If not can you make it consistent?

**Comment by feihong** [comment]
You must be using a different version of webpack than I am. It actually complains if I leave out the mode field. I'm using 4.15.1. What do you get if you run `yarn webpack --version`?

Yarn isn't used on Glitch.
